# Generated by Django 5.1 on 2024-10-13 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='queue_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.queue'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='estimated_time',
            field=models.IntegerField(default=None),
        ),
    ]
