# Generated by Django 5.1.2 on 2024-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_queue_name_entry_queue_entry_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
